# Base configs
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Portfolio photo"
subtitle: "Ouvrez les yeux !"
author: "Ciel"
header:
 title: "Photographie"
 subtitle: "Par ciel"
footer:
 name: "Bonjour, je suis Ciel"
 bio: "Je suis ingénieur en informatique et photographe. Le monde est rempli de belles choses et une photo peut en dire tellement"

social_urls:
  linkedin: "https://www.linkedin.com/in/jean-manoury"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
